### ISSUE TITLE
Document Software Requirements, create requirements.md

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#10]
Using the [Software Requirements Document](https://codefellows.github.io/common_curriculum/projects/SoftwareReqs), create a new file within your main GH repo named `requirements.md`. Include in this doc the required information for your software requirements for your project as a whole.

**Comment by KasonBraley** [comment]
Closed by https://github.com/cf-301-group-2021/entertainment-tracker/commit/ce49b80f3336900f040552a6465e06f8ac90b9fb
