### ISSUE TITLE
Create Domain Model, add to README.md

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#11]
Draw out the entities for your project and how they are related to each other. Determine the relationships between the functions/methods and entities of your app.

Include in your domain model the names and data types of your entities and their properties.

Do some research on domain modeling and create your own diagram that represents your app. Here are some helpful resources as a starting point:

- [Brief introduction to Domain Modeling](https://medium.com/@olegchursin/a-brief-introduction-to-domain-modeling-862a30b38353)
- [Domain Modeling](https://www.scaledagileframework.com/domain-modeling/)
- [Domain driven architecture diagram](https://medium.com/nick-tune-tech-strategy-blog/domain-driven-architecture-diagrams-139a75acb578)

Include this domain model in the README.md file located in your project’s GitHub repo.

**Comment by KasonBraley** [comment]
Closed by https://github.com/cf-301-group-2021/entertainment-tracker/commit/ce49b80f3336900f040552a6465e06f8ac90b9fb
