### ISSUE TITLE
Create Database Schema Diagram, add to README.md

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#12]
If you are using a database of any kind in your project, draft out what your schema will look like by creating a diagram of all your application data models, each in it’s own collection (or table).

Be sure to identify the relationships (if any) between each of your data models:

1. Does a single item in your database “belong to” just one other item in your database? For example, a person has one passport, and a passport belongs to a single person.
2. Does a item in your database “belong to” multiple other items in your database? For example, a house has many residents, and each resident has one primary house.
3. Do many items in your database relate to many other items in your database? For example, a band has many musicians, and a musician can be in many bands.
4. 

Also, include for each separate collection:

1. The name of each property stored in the collection.
2. The required data type.
3. An indication if this collection is associated with another collection.

Include this diagram in your README.md, accompanied by an explanation of each data model and it’s responsibility in the application.

**Comment by KasonBraley** [comment]
Closed by https://github.com/cf-301-group-2021/entertainment-tracker/commit/ce49b80f3336900f040552a6465e06f8ac90b9fb
