### ISSUE TITLE
User Story: MVP - Search

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#2]
Title - MVP - Search

- As a user, I want to be able to search for a TV show in a variety of ways

Feature Tasks 

- Create a form component to search for a TV show
- Create API to connect to large TV show database
- Render results based on form component input

Acceptance Tests
- Given a home page, when user clicks on the Search nav item, the user should be taken to the Search page
- Given the Search form, the user should be able to search by a variety of characteristics of a TV show
- Given user input, the results should render at least one show that meets the criteria of the user input

**Comment by KasonBraley** [comment]
Searching by title has been implemented via PR https://github.com/cf-301-group-2021/entertainment-tracker/pull/20

**Comment by KasonBraley** [comment]
Search by title is what we were able to accomplish during project week.
