### ISSUE TITLE
User Story: MVP - Release Dates

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#6]
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

**Comment by KasonBraley** [comment]
Title: Release dates

User Story sentence:
As a user, I want to be able to be reminded when the next episode/season of a TV show is being released.
 
Feature Tasks:
- Create a simple component that resides as a sub component in the `TVShow` component. This component displays the days till the next release. Also a small calendar image of the date.
- Do some math logic to calculate the remaining days from the current days date.


Acceptance Tests:
- If there is no next release date from `TVmaze` then do not run the calculation logic.
- Given a `tvshow` card is shown on the page, then the user will be able to see the upcoming release date for that show if available.

**Comment by KasonBraley** [comment]
Unable to complete this reminder feature during project week. Current closest feature is the tv Show card displays the day and time the show airs on.
